var listofcapitals = [{"k": "Abu Dhabi","v" :"United Arab Emirates", "d":""},
                { "k":"Abuja","v" :"Nigeria", "d":""},
{  "k":"Accra","v" :"Ghana", "d":""},
{  "k":"Adamstown","v" :"Pitcairn Islands", "d":"British Overseas Territory"},
{  "k":"Addis Ababa","v" :"Ethiopia", "d":""},
{  "k":"Algiers","v" :"Algeria", "d":""},
{  "k":"Alofi","v" :"Niue", "d":"Self-governing in free association with New Zealand."},
{  "k":"Amman","v" :"Jordan", "d":""},
{  "k":"Amsterdam","v" :"Netherlands", "d":""},
{  "k":"Andorra la Vella","v" :"Andorra", "d":""},
{  "k":"Ankara","v" :"Turkey", "d":""},
{  "k":"Antananarivo","v" :"Madagascar", "d":""},
{  "k":"Apia","v" :"Samoa", "d":""},
{  "k":"Ashgabat","v" :"Turkmenistan", "d":""},
{  "k":"Asmara","v" :"Eritrea", "d":""},
{  "k":"Astana","v" :"Kazakhstan", "d":""},
{  "k":"Asunción","v" :"Paraguay", "d":""},
{  "k":"Athens","v" :"Greece", "d":""},
{  "k":"Avarua","v" :"Cook Islands", "d":"Self-governing in free association with New Zealand."},
{  "k":"Baghdad","v" :"Iraq", "d":""},
{  "k":"Baku","v" :"Azerbaijan", "d":""},
{  "k":"Bamako","v" :"Mali", "d":""},
{  "k":"Bandar Seri Begawan","v" :"Brunei", "d":""},
{  "k":"Bangkok","v" :"Thailand", "d":""},
{  "k":"Bangui","v" :"Central African Republic", "d":""},
{  "k":"Banjul","v" :"Gambia", "d":""},
{  "k":"Basseterre","v" :"Saint Kitts and Nevis", "d":""},
{  "k":"Beijing","v" :"China [a]", "d":""},
{  "k":"Beirut","v" :"Lebanon", "d":""},
{  "k":"Belfast","v" :"Northern Ireland", "d":"Country of the United Kingdom"},
{  "k":"Belgrade","v" :"Serbia", "d":""},
{  "k":"Belmopan","v" :"Belize", "d":""},
{  "k":"Berlin","v" :"Germany", "d":""},
{  "k":"Bern","v" :"Switzerland", "d":""},
{  "k":"Bishkek","v" :"Kyrgyzstan", "d":""},
{  "k":"Bissau","v" :"Guinea-Bissau", "d":""},
{  "k":"Bogotá","v" :"Colombia", "d":""},
{  "k":"Brasilia","v" :"Brazil", "d":""},
{  "k":"Bratislava","v" :"Slovakia", "d":""},
{  "k":"Brazzaville","v" :"Republic of the Congo", "d":""},
{  "k":"Bridgetown","v" :"Barbados", "d":""},
{  "k":"Brussels","v" :"Belgium", "d":""},
{  "k":"Bucharest","v" :"Romania", "d":""},
{  "k":"Budapest","v" :"Hungary", "d":""},
{  "k":"Buenos Aires","v" :"Argentina", "d":""},
{  "k":"Bujumbura","v" :"Burundi", "d":""},
{  "k":"Cairo","v" :"Egypt", "d":""},
{  "k":"Canberra","v" :"Australia", "d":""},
{  "k":"Caracas","v" :"Venezuela", "d":""},
{  "k":"Cardiff","v" :"Wales", "d":"Country of the United Kingdom"},
{  "k":"Castries","v" :"Saint Lucia", "d":""},
{  "k":"Cayenne","v" :"French Guiana", "d":"Overseas department of France"},
{  "k":"Charlotte Amalie","v" :"United States Virgin Islands", "d":"Territory of the United States"},
{  "k":"Chisinau","v" :"Moldova", "d":""},
{  "k":"Cockburn Town","v" :"Turks and Caicos Islands", "d":"British Overseas Territory"},
{  "k":"Conakry","v" :"Guinea", "d":""},
{  "k":"Copenhagen","v" :"Denmark", "d":""},
{  "k":"Dakar","v" :"Senegal", "d":""},
{  "k":"Damascus","v" :"Syria", "d":""},
{  "k":"Dhaka","v" :"Bangladesh", "d":""},
{  "k":"Dili","v" :"East Timor (Timor-Leste)", "d":""},
{  "k":"Djibouti","v" :"Djibouti", "d":""},
{  "k":"Dodoma (official); mostly de facto","v" :"Tanzania", "d":""},
{  "k":"Dar es Salaam (former; some government offices remaining)","v" :"Tanzania", "d":""},
{  "k":"Doha","v" :"Qatar", "d":""},
{  "k":"Douglas","v" :"Isle of Man", "d":"British Crown Dependency"},
{  "k":"Dublin","v" :"Ireland", "d":""},
{  "k":"Dushanbe","v" :"Tajikistan", "d":""},
{  "k":"Edinburgh","v" :"Scotland", "d":"Country of the United Kingdom"},
{  "k":"Edinburgh of the Seven Seas","v" :"Tristan da Cunha", "d":"British Overseas Territory"},
{  "k":"El Aaiún (declared)","v" :"Sahrawi Arab Democratic Republic [c]", "d":"The Sahrawi Republic, recognised by 82 states, claims the mostly Moroccan controlled Western Sahara. Moroccan controlled territory includes El Aaiún, and Morocco claims all Sahrawi controlled territory. The Sahrawi government resides in exile in Tindouf, Algeria.[1]"},
{  "k":"Episkopi Cantonment","v" :"Akrotiri and Dhekelia", "d":"British Overseas Territory"},
{  "k":"Flying Fish Cove","v" :"Christmas Island", "d":"External territory of Australia"},
{  "k":"Freetown","v" :"Sierra Leone", "d":""},
{  "k":"Funafuti","v" :"Tuvalu", "d":""},
{  "k":"Gaborone","v" :"Botswana", "d":""},
{  "k":"George Town","v" :"Cayman Islands", "d":"British Overseas Territory"},
{  "k":"Georgetown","v" :"Ascension Island", "d":""},
{  "k":"Georgetown","v" :"Guyana", "d":""},
{  "k":"Gibraltar","v" :"Gibraltar", "d":"British Overseas Territory"},
{  "k":"Grytviken","v" :"South Georgia and the South Sandwich Islands", "d":"British Overseas Territory"},
{  "k":"Guatemala City","v" :"Guatemala", "d":""},
{  "k":"Gustavia","v" :"Saint Barthélemy", "d":"Overseas collectivity of France"},
{  "k":"Hagåtña","v" :"Guam", "d":"Territory of the United States"},
{  "k":"Hamilton","v" :"Bermuda", "d":"British Overseas Territory"},
{  "k":"Hanga Roa","v" :"Easter Island", "d":"Special territory of Chile"},
{  "k":"Hanoi","v" :"Vietnam", "d":""},
{  "k":"Harare","v" :"Zimbabwe", "d":""},
{  "k":"Hargeisa","v" :"Somaliland [b]", "d":"De facto independent state not diplomatically recognized by any other state, claimed in whole by the Somali Republic.[2]"},
{  "k":"Havana","v" :"Cuba", "d":""},
{  "k":"Helsinki","v" :"Finland", "d":""},
{  "k":"Honiara","v" :"Solomon Islands", "d":""},
{  "k":"Islamabad","v" :"Pakistan", "d":""},
{  "k":"Jakarta","v" :"Indonesia", "d":""},
{  "k":"Jamestown","v" :"Saint Helena", "d":"British Overseas Territory"},
{  "k":"Jerusalem (declared)[f]","v" :"State of Palestine", "d":""},
{  "k":"Ramallah and Gaza (de facto)","v" :"State of Palestine", "d":"The State of Palestine claims the territories occupied by Israel since the Six-Day War in 1967, with East Jerusalem as its capital. The proclaimed state is currently occupied by Israel and has no effective control over the territories it claims. Administration is based in Ramallah and Gaza, rather than Jerusalem. All members of the United Nations regard East Jerusalem as occupied territory, and the Organisation of Islamic Cooperation, the Arab League, the Non-Aligned Movement and the European Union recognise it as the capital of a future Palestinian state.[5]"},
{  "k":"Jerusalem (declared, de facto)[f]","v" :"Israel", "d":"Jerusalem Law states that 'Jerusalem, complete and united, is the capital of Israel', and the city serves as the seat of the government, home to the president's residence, government offices, supreme court, and parliament. United Nations Security Council Resolution 478 declared the Jerusalem Law 'null and void' and called on member states to withdraw their diplomatic missions from Jerusalem. The United Nations and all member states maintain their embassies in other cities such as Tel Aviv, Ramat Gan, and Herzliya, and do not recognise Jerusalem as the capital.[3] Many countries officially adhere to the proposal that Jerusalem have international status, as called for in the Partition Plan of 1947.[4] The Palestinian National Authority claims East Jerusalem as the capital of a future Palestinian state."},
{  "k":"Juba","v" :"South Sudan", "d":""},
{  "k":"Kabul","v" :"Afghanistan", "d":""},
{  "k":"Kampala","v" :"Uganda", "d":""},
{  "k":"Kathmandu","v" :"Nepal", "d":""},
{  "k":"Khartoum","v" :"Sudan", "d":""},
{  "k":"Kiev","v" :"Ukraine", "d":""},
{  "k":"Kigali","v" :"Rwanda", "d":""},
{  "k":"Kingston","v" :"Jamaica", "d":""},
{  "k":"Kingston","v" :"Norfolk Island", "d":"External territory of Australia"},
{  "k":"Kingstown","v" :"Saint Vincent and the Grenadines", "d":""},
{  "k":"Kinshasa","v" :"Democratic Republic of the Congo", "d":""},
{  "k":"Kuala Lumpur","v" :"Malaysia (official)", "d":""},
{  "k":"Kuwait City","v" :"Kuwait", "d":""},
{  "k":"Libreville","v" :"Gabon", "d":""},
{  "k":"Lilongwe","v" :"Malawi", "d":""},
{  "k":"Lima","v" :"Peru", "d":""},
{  "k":"Lisbon","v" :"Portugal", "d":""},
{  "k":"Ljubljana","v" :"Slovenia", "d":""},
{  "k":"Lomé","v" :"Togo", "d":""},
{  "k":"London","v" :"United Kingdom;  England", "d":"London is both the capital of England, a Country of the United Kingdom, and of the United Kingdom itself, a sovereign state."},
{  "k":"Luanda","v" :"Angola", "d":""},
{  "k":"Lusaka","v" :"Zambia", "d":""},
{  "k":"Luxembourg","v" :"Luxembourg", "d":""},
{  "k":"Madrid","v" :"Spain", "d":""},
{  "k":"Majuro","v" :"Marshall Islands", "d":""},
{  "k":"Malabo","v" :"Equatorial Guinea", "d":""},
{  "k":"Malé","v" :"Maldives", "d":""},
{  "k":"Managua","v" :"Nicaragua", "d":""},
{  "k":"Manama","v" :"Bahrain", "d":""},
{  "k":"Manila","v" :"Philippines", "d":""},
{  "k":"Maputo","v" :"Mozambique", "d":""},
{  "k":"Marigot","v" :"Saint Martin","d":"Overseas collectivity of France"},
{  "k":"Maseru","v" :"Lesotho","d":""},
{  "k":"Mata-Utu","v" :"Wallis and Futuna","d":"Overseas collectivity of France"},
{  "k":"Lobamba (royal and legislative)","v" :"Swaziland", "d":""},
{  "k":"Melekeok","v" :"Palau", "d":""},
{  "k":"Mexico City","v" :"Mexico", "d":""},
{  "k":"Minsk","v" :"Belarus", "d":""},
{  "k":"Mogadishu","v" :"Somalia", "d":""},
{  "k":"Monaco","v" :"Monaco", "d":"City-state"},
{  "k":"Monrovia","v" :"Liberia", "d":""},
{  "k":"Montevideo","v" :"Uruguay", "d":""},
{  "k":"Moroni","v" :"Comoros", "d":""},
{  "k":"Moscow","v" :"Russia", "d":""},
{  "k":"Muscat","v" :"Oman", "d":""},
{  "k":"N'Djamena","v" :"Chad", "d":""},
{  "k":"Nairobi","v" :"Kenya", "d":""},
{  "k":"Nassau","v" :"Bahamas", "d":""},
{  "k":"Naypyidaw","v" :"Myanmar", "d":""},
{  "k":"New Delhi","v" :"India", "d":""},
{  "k":"Niamey","v" :"Niger", "d":""},
{  "k":"Nicosia","v" :"Cyprus", "d":""},
{  "k":"Nicosia","v" :"Northern Cyprus", "d":"De facto independent state that is recognised only by Turkey. Northern Cyprus is claimed in whole by the Republic of Cyprus.[6]"},
{  "k":"Nouakchott","v" :"Mauritania", "d":""},
{  "k":"Nouméa","v" :"New Caledonia", "d":"Sui generis collectivity of France"},
{  "k":"Nukuʻalofa","v" :"Tonga", "d":""},
{  "k":"Nuuk","v" :"Greenland", "d":"Self-governing territory of the Danish Realm"},
{  "k":"Oranjestad","v" :"Aruba", "d":"Self-governing part of the Kingdom of the Netherlands"},
{  "k":"Oslo","v" :"Norway", "d":""},
{  "k":"Ottawa","v" :"Canada", "d":""},
{  "k":"Ouagadougou","v" :"Burkina Faso", "d":""},
{  "k":"Pago Pago","v" :"American Samoa", "d":"Territory of the United States"},
{  "k":"Palikir","v" :"Federated States of Micronesia", "d":""},
{  "k":"Panama City","v" :"Panama", "d":""},
{  "k":"Papeete","v" :"French Polynesia", "d":"Overseas collectivity of France"},
{  "k":"Paramaribo","v" :"Suriname", "d":""},
{  "k":"Paris","v" :"France", "d":""},
{  "k":"Philipsburg","v" :"Sint Maarten", "d":"Self-governing part of the Kingdom of the Netherlands"},
{  "k":"Phnom Penh","v" :"Cambodia", "d":""},
{  "k":"Brades Estate (de facto)","v" :"Montserrat", "d":"British Overseas Territory"},
{  "k":"Podgorica","v" :"Montenegro", "d":""},
{  "k":"Port Louis","v" :"Mauritius", "d":""},
{  "k":"Port Moresby","v" :"Papua New Guinea", "d":""},
{  "k":"Port of Spain","v" :"Trinidad and Tobago", "d":""},
{  "k":"Port Vila","v" :"Vanuatu", "d":""},
{  "k":"Port-au-Prince","v" :"Haiti", "d":""},
{  "k":"Cotonou (de facto)","v" :"Benin", "d":""},
{  "k":"Prague","v" :"Czech Republic", "d":""},
{  "k":"Praia","v" :"Cape Verde", "d":""},
{  "k":"Pretoria (executive)","v" :"South Africa", "d":""},
{  "k":"Bloemfontein (judicial)","v" :"South Africa", "d":""},
{  "k":"Cape Town (legislative)","v" :"South Africa", "d":""},
{  "k":"Pristina","v" :"Kosovo[g]", "d":"De facto independent state that is recognised by 92 UN member states and by Taiwan. Claimed in whole by the Republic of Serbia as part of its Autonomous Province of Kosovo and Metohija. Republic of Kosovo has de facto control over most of the territory, with limited control in North Kosovo."},
{  "k":"Pyongyang","v" :"North Korea", "d":""},
{  "k":"Quito","v" :"Ecuador", "d":"Highest official capital.[7]"},
{  "k":"Rabat","v" :"Morocco", "d":""},
{  "k":"Reykjavík","v" :"Iceland", "d":""},
{  "k":"Riga","v" :"Latvia", "d":""},
{  "k":"Riyadh","v" :"Saudi Arabia", "d":""},
{  "k":"Road Town","v" :"British Virgin Islands", "d":"British Overseas Territory"},
{  "k":"Rome","v" :"Italy", "d":""},
{  "k":"Roseau","v" :"Dominica", "d":""},
{  "k":"Saipan","v" :"Northern Mariana Islands", "d":"Territory of the United States"},
{  "k":"San José","v" :"Costa Rica", "d":""},
{  "k":"San Juan","v" :"Puerto Rico", "d":"Territory of the United States"},
{  "k":"San Marino","v" :"San Marino", "d":""},
{  "k":"San Salvador","v" :"El Salvador", "d":""},
{  "k":"Sanaá","v" :"Yemen", "d":""},
{  "k":"Santiago","v" :"Chile", "d":""},
{  "k":"Santo Domingo","v" :"Dominican Republic", "d":""},
{  "k":"Sarajevo","v" :"Bosnia and Herzegovina", "d":""},
{  "k":"Seoul","v" :"South Korea", "d":""},
{  "k":"Singapore","v" :"Singapore", "d":"City-state"},
{  "k":"Skopje","v" :"Macedonia", "d":""},
{  "k":"Sofia","v" :"Bulgaria", "d":""},
{  "k":"Colombo (previous capital; has some government offices)","v" :"Sri Lanka", "d":""},
{  "k":"St. George's","v" :"Grenada", "d":""},
{  "k":"St. Helier","v" :"Jersey", "d":"British Crown Dependency"},
{  "k":"St. John's","v" :"Antigua and Barbuda", "d":""},
{  "k":"St. Peter Port","v" :"Guernsey", "d":"British Crown Dependency"},
{  "k":"St. Pierre","v" :"Saint Pierre and Miquelon", "d":"Overseas collectivity of France"},
{  "k":"Stanley","v" :"Falkland Islands", "d":"British Overseas Territory"},
{  "k":"Stepanakert","v" :"Nagorno-Karabakh Republic", "d":"The self-declared country remains diplomatically unrecognised by UN-member states, including Armenia. Transnistria, South Ossetia, and Abkhazia, all UN non-member states, recognise the state."},
{  "k":"Stockholm","v" :"Sweden", "d":""},
{  "k":"La Paz (administrative)","v" :"Bolivia", "d":"La Paz is the highest administrative capital, higher than Quito.[7]"},
{  "k":"Sukhumi","v" :"Abkhazia", "d":"De facto independent state recognised by Russia, Nauru, Nicaragua, Venezuela, South Ossetia and Transnistria. Claimed in whole by Republic of Georgia as the Autonomous Republic of Abkhazia."},
{  "k":"Suva","v" :"Fiji", "d":""},
{  "k":"São Tomé","v" :"São Tomé and Príncipe", "d":""},
{  "k":"Taipei","v" :"Taiwan", "d":"Officially the Republic of China (ROC), it has been competing for recognition with the People's Republic of China (PRC) as the sole Chinese government since 1949. Taiwan controls the island of Taiwan and its associated islands, Quemoy, Matsu, the Pratas, and part of the Spratly Islands[8] The territory of Taiwan is claimed in whole by China.[9] The Republic of China participates in the World Health Organization and a number of non-UN international organizations such as the World Trade Organization, International Olympic Committee and others under a variety of pseudonyms, most commonly Chinese Taipei."},
{  "k":"Tallinn","v" :"Estonia", "d":""},
{  "k":"Tarawa","v" :"Kiribati", "d":""},
{  "k":"Tashkent","v" :"Uzbekistan", "d":""},
{  "k":"Tbilisi","v" :"Georgia", "d":""},
{  "k":"Tegucigalpa","v" :"Honduras", "d":""},
{  "k":"Tehran","v" :"Iran", "d":""},
{  "k":"The Valley","v" :"Anguilla", "d":"British Overseas Territory"},
{  "k":"Thimphu","v" :"Bhutan", "d":""},
{  "k":"Tirana","v" :"Albania", "d":""},
{  "k":"Tiraspol","v" :"Transnistria", "d":"De facto independent state, not recognized by any UN-member, but by Abkhazia and South Ossetia. Claimed in whole by the Republic of Moldova as the Territorial Unit of Transnistria."},
{  "k":"Tokyo","v" :"Japan", "d":""},
{  "k":"Tripoli","v" :"Libya", "d":""},
{  "k":"Tskhinvali","v" :"South Ossetia", "d":"De facto independent state recognised by Russia, Nicaragua, Nauru, Venezuela, Abkhazia and Transnistria. Claimed in whole by the Republic of Georgia as the Provisional Administrative Entity of South Ossetia."},
{  "k":"Tunis","v" :"Tunisia", "d":""},
{  "k":"Tórshavn","v" :"Faroe Islands", "d":"Self-governing territory of the Danish Realm"},
{  "k":"Ulan Bator","v" :"Mongolia", "d":""},
{  "k":"Vaduz","v" :"Liechtenstein", "d":""},
{  "k":"Valletta","v" :"Malta", "d":""},
{  "k":"Vatican City","v" :"Vatican City", "d":"City-state"},
{  "k":"Victoria","v" :"Seychelles", "d":""},
{  "k":"Vienna","v" :"Austria", "d":""},
{  "k":"Vientiane","v" :"Laos", "d":""},
{  "k":"Vilnius","v" :"Lithuania", "d":""},
{  "k":"Warsaw","v" :"Poland", "d":""},
{  "k":"Washington, D.C.","v" :"United States", "d":""},
{  "k":"Wellington","v" :"New Zealand", "d":""},
{  "k":"West Island","v" :"Cocos (Keeling) Islands", "d":"External territory of Australia"},
{  "k":"Willemstad","v" :"Curaçao", "d":"Self-governing part of the Kingdom of the Netherlands"},
{  "k":"Windhoek","v" :"Namibia", "d":""},
{  "k":"Abidjan (former capital; still has many government offices)","v" :"Ivory Coast", "d":""},
{  "k":"Yaoundé","v" :"Cameroon", "d":""},
{  "k":"Yaren (de facto)","v" :"Nauru", "d":"Country does not have an official capital; however, the government offices are in Yaren."},
{  "k":"Yerevan","v" :"Armenia", "d":""}];

